# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-31 02:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20170526_0132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2017, 5, 31, 2, 40, 3, 600532, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
